name: GitHub Actions Actualizar README
on: [push]
jobs:
  Actualizar-README:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your your repository is ${{ github.repository }}."
      - run: echo mkdocs gh-deploy